import { cn } from "@/lib/utils";

// Reference button — matches detected tone (slightly-rounded corners,
// soft shadow). Generated by Slurper as a design starting point;
// replace with shadcn/ui Button and keep these tone choices.
export function Button({
  className,
  ...props
}: React.ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      className={cn(
        "inline-flex items-center justify-center px-5 py-2.5 font-medium",
        "rounded-[var(--radius)] bg-[var(--primary)] text-white shadow-[var(--shadow)]",
        "transition-all duration-200 hover:opacity-90 hover:-translate-y-0.5 active:translate-y-0",
        className,
      )}
      {...props}
    />
  );
}
